spring.application.name=cit-senai


spring.datasource.url=jdbc:postgresql://servidor-cti.postgres.database.azure.com:5432/cti_provedor?sslmode=require
spring.datasource.username=raphaelreche
spring.datasource.password=C@raiovaisifude

spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true



